package pokemons

var Pokemons = map[string]map[string]interface{} {
	"Bulbizarre": {
		"Type": []string{"Herbe", "Poison"},
		"HP": 22,
		"MaxHP": 22,
		"Dmg": 4,
	},
	"Salamèche": {
		"Type": []string{"Feu"},
		"HP": 24,
		"MaxHP": 24,
		"Dmg": 6,
	},
	"Carapuce": {
		"Type": []string{"Eau"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 5,
	},
	"Pikachu": {
		"Type": []string{"Electrique"},
		"HP": 25,
		"MaxHP": 25,
		"Dmg": 5,
	},
	"Aspicot": {
		"Type": []string{"Bug", "Poison"},
		"HP": 16,
		"MaxHP": 16,
		"Dmg": 2,
	},
	"Ratata": {
		"Type": []string{"Normal"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 4,
	},
	"Sabelette": {
		"Type": []string{"Sol"},
		"HP": 19,
		"MaxHP": 19,
		"Dmg": 5,
	},
	"Nidoran": {
		"Type": []string{"Poison"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 4,
	},
	"Goupix": {
		"Type": []string{"Feu"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 6,
	},
	"Psykokwak": {
		"Type": []string{"Eau"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 6,
	},
	"Férosinge": {
		"Type": []string{"Combat"},
		"HP": 19,
		"MaxHP": 19,
		"Dmg": 7,
	},
	"Abra": {
		"Type": []string{"Psy"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 6,
	},
	"Racaillou": {
		"Type": []string{"Pierre", "Sol"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 4,
	},
	"Magnéti": {
		"Type": []string{"Electrique", "Acier"},
		"HP": 24,
		"MaxHP": 24,
		"Dmg": 5,
	},
	"Mr. Mime": {
		"Type": []string{"Psy", "Fée"},
		"HP": 24,
		"MaxHP": 24,
		"Dmg": 5,
	},
	"Évoli": {
		"Type": []string{"Normal"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 4,
	},
	"Aquali": {
		"Type": []string{"Eau"},
		"HP": 21,
		"MaxHP": 21,
		"Dmg": 4,
	},
	"Voltali": {
		"Type": []string{"Electrique"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 5,
	},
	"Pyroli": {
		"Type": []string{"Feu"},
		"HP": 22,
		"MaxHP": 22,
		"Dmg": 6,
	},
	"Nymphali": {
		"Type": []string{"Fée"},
		"HP": 21,
		"MaxHP": 21,
		"Dmg": 5,
	},
	"Mentali": {
		"Type": []string{"Psy"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 4,
	},
	"Phyllali": {
		"Type": []string{"Herbe"},
		"HP": 22,
		"MaxHP": 22,
		"Dmg": 4,
	},
	"Givrali": {
		"Type": []string{"Glace"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 5,
	},
	"Noctali": {
		"Type": []string{"Ténèbres"},
		"HP": 25,
		"MaxHP": 25,
		"Dmg": 7,
	},
	"Mew": {
		"Type": []string{"Psy"},
		"HP": 27,
		"MaxHP": 27,
		"Dmg": 8,
	},
	"Lippoutou": {
		"Type": []string{"Glace", "Psy"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 6,
	},
	"Oniglali": {
		"Type": []string{"Glace"},
		"HP": 19,
		"MaxHP": 19,
		"Dmg": 4,
	},
	"Ponyta": {
		"Type": []string{"Feu"},
		"HP": 22,
		"MaxHP": 22,
		"Dmg": 5,
	},
	"Hypotrempe": {
		"Type": []string{"Eau"},
		"HP": 21,
		"MaxHP": 21,
		"Dmg": 4,
	},
	"Sorbébé": {
		"Type": []string{"Glace"},
		"HP": 18,
		"MaxHP": 18,
		"Dmg": 4,
	},
	"Wattouat": {
		"Type": []string{"Electrique"},
		"HP": 20,
		"MaxHP": 20,
		"Dmg": 5,
	},
	"Tadmorv": {
		"Type": []string{"Poison"},
		"HP": 27,
		"MaxHP": 27,
		"Dmg": 6,
	},
	"Smogo": {
		"Type": []string{"Poison"},
		"HP": 23,
		"MaxHP": 23,
		"Dmg": 4,
	},
	"Voltorbe": {
		"Type": []string{"Electrique"},
		"HP": 21,
		"MaxHP": 21,
		"Dmg": 4,
	},
	"Magicarpe": {
		"Type": []string{"Eau"},
		"HP": 14,
		"MaxHP": 14,
		"Dmg": 3,
	},
	"Polarhume": {
		"Type": []string{"Glace"},
		"HP": 18,
		"MaxHP": 18,
		"Dmg": 4,
	},
	"Poussifeu": {
		"Type": []string{"Feu"},
		"HP": 19,
		"MaxHP": 19,
		"Dmg": 5,
	},
}